import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { BarChart3, Bell, BookOpen, CalendarDays, ChevronRight, ClipboardCheck, GraduationCap, LayoutDashboard, LogOut, Menu, Plus, Search, Settings, Users, WalletCards, X } from 'lucide-react';
import { api, type Overview, type Student, type User } from './api';

function App() {
  const [user, setUser] = useState<User | null>(() => { const value = localStorage.getItem('user'); return value ? JSON.parse(value) as User : null; });
  return <Routes><Route path="/login" element={user ? <Navigate to="/" /> : <Login onLogin={setUser} />} /><Route path="/*" element={user ? <Shell user={user} onLogout={() => { localStorage.clear(); setUser(null); }} /> : <Navigate to="/login" />} /></Routes>;
}

function Login({ onLogin }: { onLogin: (u: User) => void }) {
  const [username, setUsername] = useState('admin'); const [password, setPassword] = useState('Admin@123'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const nav = useNavigate();
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const result = await api.login(username, password); localStorage.setItem('access_token', result.access_token); localStorage.setItem('user', JSON.stringify(result.user)); onLogin(result.user); nav('/'); } catch (e) { setError(e instanceof Error ? e.message : 'Đăng nhập thất bại.'); } finally { setBusy(false); } }
  return <main className="login-page"><section className="login-art"><div className="brand brand-light"><span className="brand-mark">空</span><span>Sora Academy</span></div><div className="hero-copy"><span className="eyebrow">日本語センター</span><h1>Mỗi hành trình<br/>bắt đầu từ một<br/><em>ước mơ.</em></h1><p>Không gian quản lý học tập tiếng Nhật hiện đại, kết nối giáo viên và học viên trên cùng một hành trình.</p></div><div className="japan-sun"/><div className="mountain mountain-one"/><div className="mountain mountain-two"/></section><section className="login-panel"><form className="login-card" onSubmit={submit}><div className="mobile-brand brand"><span className="brand-mark">空</span><span>Sora Academy</span></div><span className="eyebrow ink">CHÀO MỪNG TRỞ LẠI</span><h2>Đăng nhập</h2><p>Nhập thông tin tài khoản để tiếp tục.</p><label>Tên đăng nhập<input value={username} onChange={e => setUsername(e.target.value)} autoFocus /></label><label>Mật khẩu<input type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Đang xác thực…' : 'Đăng nhập'} <ChevronRight size={18}/></button><small>Tài khoản mẫu: admin / Admin@123</small></form></section></main>;
}

const menu = [{ to: '/', label: 'Tổng quan', icon: LayoutDashboard }, { to: '/hoc-sinh', label: 'Học sinh', icon: Users }, { to: '/lop-hoc', label: 'Lớp học', icon: BookOpen }, { to: '/lich-hoc', label: 'Lịch học', icon: CalendarDays }, { to: '/diem-danh', label: 'Điểm danh', icon: ClipboardCheck }, { to: '/hoc-phi', label: 'Học phí', icon: WalletCards }, { to: '/bao-cao', label: 'Báo cáo', icon: BarChart3 }];
function Shell({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [open, setOpen] = useState(false);
  return <div className="app"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand"><span className="brand-mark">空</span><span>Sora Academy</span><button className="close-menu" onClick={() => setOpen(false)}><X/></button></div><nav>{menu.map(item => <NavLink key={item.to} to={item.to} end={item.to === '/'} onClick={() => setOpen(false)}><item.icon size={19}/>{item.label}</NavLink>)}</nav><div className="sidebar-foot"><NavLink to="/cai-dat"><Settings size={19}/>Cài đặt</NavLink><button onClick={onLogout}><LogOut size={19}/>Đăng xuất</button></div></aside><div className="workspace"><header><button className="menu-button" onClick={() => setOpen(true)}><Menu/></button><div className="header-title"><strong>Quản lý trung tâm</strong><span>Học kỳ I · 2026–2027</span></div><div className="header-user"><button className="icon-button"><Bell size={20}/><i/></button><div className="avatar">AD</div><div><strong>{user.ten_dang_nhap}</strong><span>Quản trị viên</span></div></div></header><main className="content"><Routes><Route index element={<Dashboard/>}/><Route path="hoc-sinh" element={<Students/>}/><Route path="*" element={<ComingSoon/>}/></Routes></main></div>{open && <div className="overlay" onClick={() => setOpen(false)}/>}</div>;
}

function Dashboard() {
  const [data, setData] = useState<Overview | null>(null); const [error, setError] = useState('');
  useEffect(() => { api.overview().then(setData).catch(e => setError(e instanceof Error ? e.message : 'Lỗi tải dữ liệu')); }, []);
  const cards = [{ key: 'hoc_sinh', label: 'Học sinh đang học', icon: Users, color: 'blue' }, { key: 'lop_hoc', label: 'Lớp đang hoạt động', icon: BookOpen, color: 'orange' }, { key: 'giao_vien', label: 'Giáo viên', icon: GraduationCap, color: 'green' }, { key: 'dang_ky', label: 'Đăng ký hiệu lực', icon: ClipboardCheck, color: 'purple' }] as const;
  return <><div className="page-heading"><div><span className="eyebrow ink">THỨ NĂM, 20 THÁNG 8</span><h1>Xin chào, Admin 👋</h1><p>Đây là tình hình học tập hôm nay tại trung tâm.</p></div><button className="outline"><CalendarDays size={18}/> Học kỳ I, 2026</button></div>{error && <div className="error">{error}</div>}<section className="metrics">{cards.map(c => <article className="metric" key={c.key}><div className={`metric-icon ${c.color}`}><c.icon/></div><div><span>{c.label}</span><strong>{data?.chi_so[c.key] ?? '—'}</strong><small>Đang cập nhật theo thời gian thực</small></div></article>)}</section><section className="dashboard-grid"><article className="panel"><div className="panel-title"><div><h3>Phân bổ theo cấp độ</h3><p>Số học sinh đang học từ N5 đến N1</p></div><BarChart3/></div><div className="level-chart">{['N5','N4','N3','N2','N1'].map((level, i) => { const count = data?.theo_cap_do.find(x => x.cap_do === level)?.so_luong ?? 0; const max = Math.max(...(data?.theo_cap_do.map(x => x.so_luong) ?? [1]), 1); return <div className="bar-row" key={level}><strong>{level}</strong><div><i style={{ width: `${Math.max(count / max * 100, count ? 8 : 0)}%`, animationDelay: `${i * 80}ms` }}/></div><span>{count}</span></div>; })}</div></article><article className="panel quick"><div className="panel-title"><div><h3>Truy cập nhanh</h3><p>Các tác vụ thường dùng</p></div></div><NavLink to="/hoc-sinh"><span className="quick-icon blue"><Plus/></span><div><strong>Thêm học sinh mới</strong><small>Tạo hồ sơ và xếp cấp độ</small></div><ChevronRight/></NavLink><NavLink to="/diem-danh"><span className="quick-icon orange"><ClipboardCheck/></span><div><strong>Điểm danh buổi học</strong><small>Ghi nhận chuyên cần hôm nay</small></div><ChevronRight/></NavLink><NavLink to="/hoc-phi"><span className="quick-icon green"><WalletCards/></span><div><strong>Ghi nhận học phí</strong><small>Tạo giao dịch và phiếu thu</small></div><ChevronRight/></NavLink></article></section></>;
}

function Students() {
  const [students, setStudents] = useState<Student[]>([]); const [q, setQ] = useState(''); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<Student | null>(null); const [error, setError] = useState('');
  const load = (search = q) => { setLoading(true); api.students(search).then(r => setStudents(r.data)).catch(e => setError(e instanceof Error ? e.message : 'Lỗi')).finally(() => setLoading(false)); };
  useEffect(() => { load(''); }, []);
  return <><div className="page-heading compact"><div><span className="eyebrow ink">QUẢN LÝ HỌC VỤ</span><h1>Danh sách học sinh</h1><p>Theo dõi hồ sơ, trạng thái và lộ trình JLPT.</p></div><button className="primary small" onClick={() => { setEditing(null); setModal(true); }}><Plus size={18}/> Thêm học sinh</button></div><section className="panel table-panel"><form className="toolbar" onSubmit={e => { e.preventDefault(); load(); }}><div className="search"><Search size={18}/><input placeholder="Tìm theo mã hoặc họ tên…" value={q} onChange={e => setQ(e.target.value)}/></div><button className="outline" type="submit">Tìm kiếm</button></form>{error && <div className="error">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Học sinh</th><th>Liên hệ</th><th>Cấp độ</th><th>Trạng thái</th><th/></tr></thead><tbody>{loading ? <tr><td colSpan={5} className="empty">Đang tải dữ liệu…</td></tr> : students.length === 0 ? <tr><td colSpan={5} className="empty">Không tìm thấy học sinh.</td></tr> : students.map(s => <tr key={s.id}><td><div className="student-cell"><span>{s.ho_ten.split(' ').slice(-2).map(x => x[0]).join('')}</span><div><strong>{s.ho_ten}</strong><small>{s.ma_hoc_sinh}</small></div></div></td><td><span>{s.email ?? '—'}</span><small className="block">{s.so_dien_thoai ?? ''}</small></td><td><b className={`level ${s.cap_do_hien_tai.toLowerCase()}`}>{s.cap_do_hien_tai}</b></td><td><b className={`status ${s.trang_thai === 'DANG_HOC' ? 'active' : ''}`}>{s.trang_thai.replaceAll('_', ' ')}</b></td><td><button className="text-button" onClick={() => { setEditing(s); setModal(true); }}>Chỉnh sửa</button></td></tr>)}</tbody></table></div></section>{modal && <StudentModal student={editing} onClose={() => setModal(false)} onSaved={() => { setModal(false); load(); }}/>}</>;
}

function StudentModal({ student, onClose, onSaved }: { student: Student | null; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState({ ma_hoc_sinh: student?.ma_hoc_sinh ?? '', ho_ten: student?.ho_ten ?? '', cap_do_hien_tai: student?.cap_do_hien_tai ?? 'N5', email: student?.email ?? '', so_dien_thoai: student?.so_dien_thoai ?? '', trang_thai: student?.trang_thai ?? 'DANG_HOC' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const field = (key: keyof typeof form) => ({ value: form[key], onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm({ ...form, [key]: e.target.value }) });
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { if (student) { const { ho_ten, email, so_dien_thoai, trang_thai } = form; await api.updateStudent(student.id, { ho_ten, email: email || undefined, so_dien_thoai: so_dien_thoai || undefined, trang_thai }); } else await api.createStudent({ ...form, email: form.email || undefined, so_dien_thoai: form.so_dien_thoai || undefined }); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : 'Không thể lưu'); } finally { setBusy(false); } }
  return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow ink">HỒ SƠ HỌC SINH</span><h2>{student ? 'Cập nhật học sinh' : 'Thêm học sinh mới'}</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><div className="form-grid"><label>Mã học sinh<input {...field('ma_hoc_sinh')} disabled={Boolean(student)} required/></label><label>Cấp độ<select {...field('cap_do_hien_tai')} disabled={Boolean(student)}>{['N5','N4','N3','N2','N1'].map(x => <option key={x}>{x}</option>)}</select></label><label className="full">Họ và tên<input {...field('ho_ten')} required/></label><label>Email<input type="email" {...field('email')}/></label><label>Số điện thoại<input {...field('so_dien_thoai')}/></label>{student && <label className="full">Trạng thái<select {...field('trang_thai')}><option value="DANG_HOC">Đang học</option><option value="BAO_LUU">Bảo lưu</option><option value="NGHI_HOC">Nghỉ học</option></select></label>}</div>{error && <div className="error">{error}</div>}<div className="modal-actions"><button type="button" className="outline" onClick={onClose}>Hủy</button><button className="primary small" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu hồ sơ'}</button></div></form></div>;
}

function ComingSoon() { return <section className="coming"><span className="brand-mark">空</span><h2>Phân hệ đang sẵn sàng để phát triển</h2><p>Nền dữ liệu đã có trong Prisma schema. Kết nối API tương ứng theo tài liệu thiết kế chi tiết.</p><NavLink to="/" className="primary small">Về tổng quan</NavLink></section>; }
export default App;
